/*	Project:	KirkbyMediaFundamentalsP1
 *	File:		FMODsystem.cpp
 *	Author:		Dylan Kirkby
 *	Purpose:	Implementation for FMODsystem.h
 *				Really just declares some variables...
 */

#include "FMODsystem.h"

FMOD::System* _system = 0;
FMOD_RESULT _result = FMOD_OK;

std::map<FMOD_SOUND_FORMAT, const char*> _map_format =
{
	{ FMOD_SOUND_FORMAT_NONE, "FMOD_SOUND_FORMAT_NONE"},
	{ FMOD_SOUND_FORMAT_PCM8, "FMOD_SOUND_FORMAT_PCM8"},
	{ FMOD_SOUND_FORMAT_PCM16, "FMOD_SOUND_FORMAT_PCM16"},
	{ FMOD_SOUND_FORMAT_PCM24, "FMOD_SOUND_FORMAT_PCM24"},
	{ FMOD_SOUND_FORMAT_PCM32, "FMOD_SOUND_FORMAT_PCM32"},
	{ FMOD_SOUND_FORMAT_PCMFLOAT, "FMOD_SOUND_FORMAT_PCMFLOAT"},
	{ FMOD_SOUND_FORMAT_BITSTREAM, "FMOD_SOUND_FORMAT_BITSTREAM"},
	{ FMOD_SOUND_FORMAT_MAX, "FMOD_SOUND_FORMAT_MAX"}
};

std::map<FMOD_SOUND_TYPE, const char*> _map_type =
{
	{ FMOD_SOUND_TYPE_UNKNOWN, "FMOD_SOUND_TYPE_UNKNOWN"},
	{ FMOD_SOUND_TYPE_AIFF, "FMOD_SOUND_TYPE_AIFF"},
	{ FMOD_SOUND_TYPE_ASF, "FMOD_SOUND_TYPE_ASF"},
	{ FMOD_SOUND_TYPE_DLS, "FMOD_SOUND_TYPE_DLS"},
	{ FMOD_SOUND_TYPE_FLAC, "FMOD_SOUND_TYPE_FLAC"},
	{ FMOD_SOUND_TYPE_FSB, "FMOD_SOUND_TYPE_FSB"},
	{ FMOD_SOUND_TYPE_IT, "FMOD_SOUND_TYPE_IT"},
	{ FMOD_SOUND_TYPE_MIDI, "FMOD_SOUND_TYPE_MIDI"},
	{ FMOD_SOUND_TYPE_MOD, "FMOD_SOUND_TYPE_MOD"},
	{ FMOD_SOUND_TYPE_MPEG, "FMOD_SOUND_TYPE_MPEG"},
	{ FMOD_SOUND_TYPE_OGGVORBIS, "FMOD_SOUND_TYPE_OGGVORBIS"},
	{ FMOD_SOUND_TYPE_PLAYLIST, "FMOD_SOUND_TYPE_PLAYLIST"},
	{ FMOD_SOUND_TYPE_RAW, "FMOD_SOUND_TYPE_RAW"},
	{ FMOD_SOUND_TYPE_S3M, "FMOD_SOUND_TYPE_S3M"},
	{ FMOD_SOUND_TYPE_USER, "FMOD_SOUND_TYPE_USER"},
	{ FMOD_SOUND_TYPE_WAV, "FMOD_SOUND_TYPE_WAV"},
	{ FMOD_SOUND_TYPE_XM, "FMOD_SOUND_TYPE_XM"},
	{ FMOD_SOUND_TYPE_XMA, "FMOD_SOUND_TYPE_XMA"},
	{ FMOD_SOUND_TYPE_AUDIOQUEUE, "FMOD_SOUND_TYPE_AUDIOQUEUE"},
	{ FMOD_SOUND_TYPE_AT9, "FMOD_SOUND_TYPE_AT9"},
	{ FMOD_SOUND_TYPE_VORBIS, "FMOD_SOUND_TYPE_VORBIS"},
	{ FMOD_SOUND_TYPE_MEDIA_FOUNDATION, "FMOD_SOUND_TYPE_MEDIA_FOUNDATION"},
	{ FMOD_SOUND_TYPE_MEDIACODEC, "FMOD_SOUND_TYPE_MEDIACODEC"},
	{ FMOD_SOUND_TYPE_FADPCM, "FMOD_SOUND_TYPE_FADPCM"},
	{ FMOD_SOUND_TYPE_MAX, "FMOD_SOUND_TYPE_MAX"},
};